specUri: github.com/lovethedrake/drakespec
specVersion: v0.3.0

snippets:

  baseGoContainer: &baseGoContainer
    name: go
    image: quay.io/deis/lightweight-docker-go:v0.7.0
    sourceMountPath: /go/src/github.com/lovethedrake/drakecore
    workingDirectory: /go/src/github.com/lovethedrake/drakecore
    tty: true
    resources:
      cpu:
        maxMillicores: 2000
      memory:
        maxMegabytes: 2048

jobs:

################################################################################
# Utility jobs                                                                 #
################################################################################

  dep:
    primaryContainer:
      <<: *baseGoContainer
      command: ["dep", "ensure"]
      args: ["-v"]
    sourceMountMode: RW

################################################################################
# Test jobs                                                                    #
################################################################################

  verify-vendored-code:
    primaryContainer:
      <<: *baseGoContainer
      command: ["dep", "check"]

  test:
    primaryContainer:
      <<: *baseGoContainer
      command: ["go", "test"]
      args:
      - -timeout
      - 30s
      - -race
      - -coverprofile=/shared/coverage.txt
      - -covermode=atomic
      - ./...
      sharedStorageMountPath: /shared

  upload-coverage-report:
    primaryContainer:
      <<: *baseGoContainer
      command: ["bash", "-c"]
      args: ["bash <(curl -s https://codecov.io/bash) -f /shared/coverage.txt"]
      sharedStorageMountPath: /shared

  lint:
    primaryContainer:
      <<: *baseGoContainer
      command: ["golangci-lint", "run"]
      args: ["./..."]

################################################################################
# Pipelines                                                                    #
################################################################################

pipelines:

################################################################################
# CI pipelines                                                                 #
################################################################################

  ci:
    triggers:
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        pullRequest:
          targetBranches:
            only:
            - /.*/
        push:
          branches:
            only:
            - /.*/
    jobs:
    - name: lint
    - name: verify-vendored-code
    - name: test
    - name: upload-coverage-report
      dependencies:
      - test
