specUri: github.com/lovethedrake/drakespec
specVersion: v0.1.0

snippets:

  baseGoContainer: &baseGoContainer
    name: go
    image: quay.io/deis/lightweight-docker-go:v0.7.0
    sourceMountPath: /go/src/github.com/lovethedrake/drakecore
    workingDirectory: /go/src/github.com/lovethedrake/drakecore
    tty: true

jobs:

################################################################################
# Utility jobs                                                                 #
################################################################################

  dep:
    containers:
    - <<: *baseGoContainer
      command: dep ensure -v

################################################################################
# Test jobs                                                                    #
################################################################################

  verify-vendored-code:
    containers:
    - <<: *baseGoContainer
      command: dep check

  test:
    containers:
    - <<: *baseGoContainer
      command: go test -timeout 30s -race -coverprofile=coverage.txt -covermode=atomic ./...

  upload-coverage-report:
    containers:
    - <<: *baseGoContainer
      command: bash -c "bash <(curl -s https://codecov.io/bash)"

  lint:
    containers:
    - <<: *baseGoContainer
      command: golangci-lint run ./...

################################################################################
# Pipelines                                                                    #
################################################################################

pipelines:

################################################################################
# CI pipelines                                                                 #
################################################################################

  ci:
    triggers:
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        checkSuiteRequest:
          branches:
            only:
            - /.*/
    jobs:
    - name: lint
    - name: verify-vendored-code
    - name: test
    - name: upload-coverage-report
      dependencies:
      - test
